### ISSUE TITLE
Lazy validation envoking onChange event

### ISSUE THREAD

**Issue by cgajate** [christopherboss/vue-valid8#9]
If we have a `v-on:change` event on a select menu for instance, when triggering `validateAll` it will call that `v-on:change` when attempting to submit causing multiple API requests (or whatever business logic). Requesting an option to prevent the `onChange` event from being triggered on submit.

**Comment by christopherboss** [comment]
The cause here, is because of lazy validation. I'll see if I can disable this event trigger if the modifier for `lazy` is added to the directive.
